version: "3.9"

services:
  postgres:
    image: postgres:17.5
    container_name: sole-spot-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - sole-spot-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  sole-spot:
    build:
      context: .
      dockerfile: Dockerfile
    image: sole-spot-app
    container_name: sole-spot-container
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - K8=YES
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - DOCKER=${DOCKER}
      - SERVER_IP=${SERVER_IP}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_SENDER_NAME=${SMTP_SENDER_NAME}
      - SMTP_SENDER_EMAIL=${SMTP_SENDER_EMAIL}
    networks:
      - sole-spot-net

volumes:
  postgres-data:

networks:
  sole-spot-net:
    driver: bridge
