apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deployment
spec:
  serviceName: postgres-service  # ✅ required for StatefulSet
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbuser 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbpassword
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbname
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
