apiVersion: apps/v1
kind: Deployment
metadata:
  name: sole-spot-deployment
  labels:
    app: sole-spot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sole-spot
  template:
    metadata:
      labels:
        app: sole-spot
    spec:
      containers:
        - name: sole-spot
          image: sudhin123/sole-spot:latest
          ports:
            - containerPort: 8080
          env:
            - name: K8
              value: "YES"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbuser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: dbpassword
            - name: DB_PORT
              value: "5432"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: google_client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: google_client_secret
            - name: GOOGLE_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: google_redirect_url
            - name: DOCKER
              valueFrom:
                secretKeyRef:
                  name: secretcollection
                  key: docker
